Repository S0HYUNN/KB_Skeleton-Project, pull requests merged in 2025-04, with the labels that each got.

#7 feat: MainPage 라우팅 연결
  money_log/src/App.vue
  money_log/src/assets/logo.svg
  money_log/src/pages/HomePage.vue
  money_log/src/pages/MainPage.vue
  money_log/src/router/index.js
Labels: ✨ Feature

#12 Feature/money crud
  money_log/db.json
  money_log/index.html
  money_log/src/App.vue
  money_log/src/pages/MoneyPage.vue
  money_log/src/stores/money.js
Labels: ✨ Feature

#13 feat: 아이폰 사이즈 및 둥근 화면 테두리 적용
  money_log/public/index.html
  money_log/src/App.vue
  money_log/src/assets/main.css
  money_log/src/components/DailyMoneyLog/DailyMoneyLog.vue
  money_log/src/components/DailyMoneyLog/index.js
  money_log/src/pages/MainPage.vue
Labels: ✨ Feature

#15 Design: 디자인 수정
  money_log/src/assets/main.css
  money_log/src/components/DailyMoneyLog/DailyMoneyLog.vue
  money_log/src/pages/MainPage.vue
  money_log/src/pages/StartPage.vue
  money_log/src/router/index.js
  money_log/src/views/StartPage.vue
Labels: 🎨 Html&css

#17 Feature/spending log
  money_log/src/pages/SpendingPage.vue
Labels: ✨ Feature

#18 Feat: 로그인 페이지 구현
  money_log/src/assets/note_icon.svg
  money_log/src/pages/LoginPage.vue
  money_log/src/router/index.js
Labels: ✨ Feature

#19 Feat: 시작페이지 -> 로그인페이지 라우팅 연결, 로그인 페이지 수정
  money_log/src/pages/LoginPage.vue
  money_log/src/pages/StartPage.vue
Labels: ✨ Feature, 🔨 Refactor

#21 Feature/money crud
  money_log/db.json
  money_log/src/App.vue
  money_log/src/assets/images/PushPin.png
  money_log/src/assets/images/Vector_down.png
  money_log/src/assets/images/Vector_up.png
  money_log/src/assets/modal.css
  money_log/src/components/MoneyList.vue
  money_log/src/pages/AddMoney.vue
  money_log/src/pages/MoneyPage.vue
  money_log/src/pages/PeriodMoney.vue
  money_log/src/stores/money.js
Labels: ✨ Feature

#20 Feature/spending log
  money_log/src/pages/SpendingPage.vue
Labels: ✨ Feature, 🔨 Refactor

#22 feat: MainPage 캘린더, 가계부 요약 기능 추가
  money_log/db.json
  money_log/package-lock.json
  money_log/package.json
  money_log/src/assets/main.css
  money_log/src/components/CustomCalendar.vue
  money_log/src/components/DailyMoneyLog/DailyMoneyLog.vue
  money_log/src/components/MonthlySummary.vue
  money_log/src/main.js
  money_log/src/pages/MainPage.vue
Labels: ✨ Feature

#28 Feature/spending log
  money_log/src/assets/images/back.png
  money_log/src/assets/images/detail.png
  money_log/src/assets/images/home.png
  money_log/src/assets/images/setting.png
  money_log/src/components/BaseHeader.vue
  money_log/src/pages/SpendingPage.vue
Labels: ✨ Feature

#31 feat: 메인페이지 설정 버튼 추가
  money_log/src/components/BaseHeader.vue
  money_log/src/components/CustomCalendar.vue
  money_log/src/components/DailyMoneyLog/DailyMoneyLog.vue
  money_log/src/components/MonthlySummary.vue
  money_log/src/pages/MainPage.vue
Labels: ✨ Feature

#34 Feat: 닉네임 저장 api -> main page 상단 등록, (충돌 해결...)
  money_log/db.json
  money_log/package-lock.json
  money_log/package.json
  money_log/src/main.js
  money_log/src/pages/LoginPage.vue
  money_log/src/pages/MainPage.vue
  money_log/src/pages/UserProfileEdit.vue
Labels: 🐞 Bug, ✨ Feature

#38 Feat: "Date"
  money_log/src/components/MoneyList.vue
  money_log/src/components/TodayMoney.vue
  money_log/src/pages/MoneyPage.vue
Labels: ✨ Feature

#42 Fix: db 수정
  money_log/db.json
Labels: 🐞 Bug

#41 feat: money log db 연결
  money_log/src/pages/AddMoney.vue
  money_log/src/stores/money.js
Labels: ✨ Feature

#44 Feature/spending log
  money_log/test.json
Labels: ✨ Feature

#46 Feat: 닉네임 로그인 uuid로 구현
  money_log/db.json
  money_log/package-lock.json
  money_log/package.json
  money_log/src/pages/LoginPage.vue
Labels: ✨ Feature, 🔨 Refactor

#48 Feature/spending log
  money_log/db.json
  money_log/src/stores/money.js
  money_log/test.json
Labels: ✨ Feature

#51 fix: db.json file 수정
  money_log/db.json
Labels: 🐞 Bug

#52 LogDetail 모달기능추가
  money_log/src/assets/images/MagnifyingGlass2.svg
  money_log/src/assets/images/magnifier_icon.png
  money_log/src/assets/images/plus_button.svg
  money_log/src/components/LogDetail/LogDetailFilter.vue
  money_log/src/components/LogDetail/LogDetailForm.vue
  money_log/src/components/LogDetail/LogDetailList.vue
  money_log/src/pages/LogDetailPage.vue
Labels: ✨ Feature

#54 Feature/date
  money_log/db.json
  money_log/src/components/MoneyList.vue
  money_log/src/components/TodayMoney.vue
  money_log/src/pages/PeriodMoney.vue
  money_log/src/stores/date.js
  money_log/src/stores/money.js
Labels: ✨ Feature

#55 Feature/login api neww
  money_log/db.json
Labels: 🐞 Bug

#56 Refactor: 닉네임 해결, 닉네임 수정 페이지 경로 변경
  money_log/db.json
  money_log/src/pages/UserProfileEdit.vue
Labels: 🔨 Refactor

#57 Feature/spending log
  money_log/db.json
  money_log/src/pages/SpendingPage.vue
Labels: ✨ Feature

#61 style: money topbar 위치 수정
  money_log/src/pages/MoneyPage.vue
Labels: 🎨 Html&css

#66 Feat: "incomeCategory, expenseCategory 분류 추가"
  money_log/db.json
  money_log/src/components/DailyMoneyLog/DailyMoneyLog2.vue
  money_log/src/components/MoneyList.vue
  money_log/src/components/TodayMoney.vue
  money_log/src/pages/AddMoney.vue
  money_log/src/pages/MoneyPage.vue
  money_log/src/pages/PeriodMoney.vue
  money_log/src/stores/money.js
Labels: ✨ Feature

#72 styles: LogDetail css
  money_log/src/components/LogDetail/LogDetailFilter.vue
  money_log/src/components/LogDetail/LogDetailItem.vue
  money_log/src/components/LogDetail/LogDetailList.vue
  money_log/src/pages/LogDetailPage.vue
Labels: 🎨 Html&css
